name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.4.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
          bundler-cache: true

      - name: Run specs
        run: bundle exec rake spec

      - name: Build gem
        run: |
          mkdir -p pkg
          rm -f pkg/*.gem
          bundle exec rake build
          echo "GEM_FILE=$(ls pkg/*.gem)" >> "$GITHUB_ENV"

      - name: Publish to GitHub Packages
        if: github.event_name == 'push'
        run: |
          mkdir -p "$HOME/.gem"
          printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > "$HOME/.gem/credentials"
          chmod 0600 "$HOME/.gem/credentials"
          gem push --key github --host "https://rubygems.pkg.github.com/${OWNER}" "$GEM_FILE"
        env:
          GEM_HOST_API_KEY: ${{ format('Bearer {0}', secrets.GITHUB_TOKEN) }}
          OWNER: ${{ github.repository_owner }}
